#!/usr/bin/env bash

# AWS ACCESS KEY
export AWS_ACCESS_KEY=
export AWS_SECRET_KEY=
export AWS_KEY=$AWS_ACCESS_KEY
export AWS_SECRET=$AWS_SECRET_KEY

# EC2 REGION
export EC2_URL=

# DIGITAL OCEAN
export DIGITAL_OCEAN_TOKEN=

# POSTGRES CREDENTIALS
export POSTGRES_DB_USER=
export POSTGRES_DB_PASSWORD=
