Host homelab
    HostName 192.168.1.13
    User escrichov
	IdentityFile ~/.ssh/id_rsa


Host homelabeth
    HostName 192.168.1.13
    User escrichov
	IdentityFile ~/.ssh/id_rsa


Host homelabwifi
    HostName 192.168.1.14
    User escrichov
	IdentityFile ~/.ssh/id_rsa


Host homelabwin
    HostName 192.168.1.13
    User ce
	IdentityFile ~/.ssh/id_rsa
	UserKnownHostsFile ~/.ssh/windows.dualbootbox.known_hosts


Host homelabwineth
    HostName 192.168.1.13
    User ce
	IdentityFile ~/.ssh/id_rsa
	UserKnownHostsFile ~/.ssh/windows.dualbootbox.known_hosts


Host homelabwinwifi
    HostName 192.168.1.17
    User ce
	IdentityFile ~/.ssh/id_rsa
	UserKnownHostsFile ~/.ssh/windows.dualbootbox.known_hosts
	