cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'caskroom/drivers' # Logitech options

brew 'libxml2' # for nokogiri
brew 'coreutils'
brew 'sqlite3'
brew 'go'
brew 'govendor'
brew 'openssl'
brew 'rbenv'
brew 'ruby'
brew 'ruby-build'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'
brew 'awscli'
brew 'curl'
brew 'docker'
brew 'elixir'
brew 'erlang'
brew 'ffmpeg'
brew 'git'
brew 'heroku'
brew 'httpie'
brew 'nmap'
brew 'mysql'
brew 'python2'
brew 'python3'
brew 'redis'
brew 'rmtrash'
brew 'rust'
brew 's3cmd'
brew 'tree'
brew 'upx'
brew 'vim'
brew 'watch'
brew 'zsh'
brew 'node'
brew 'npm'
brew 'mas' # Homebrew support Mac App Store
brew 'subliminal' # Subtitles downloader
brew 'arp-scan'
brew 'fzf'
brew 'fd'
brew 'the_silver_searcher'
brew 'tig'
brew 'pgcli'
brew 'glances'
brew 'ipython'
brew 'lolcat'
brew 'tldr'
brew 'diff-so-fancy'
brew 'mackup' # Backup application preferences
brew 'htop' # View processes cpu, ram, ...
brew 'mediainfo' # View files formats
brew 'duti' # Change defaults apps for file extensions

cask 'google-chrome'
cask 'handbrake'
cask 'slack'
cask 'postico'
cask 'postman'
cask 'sketch'
cask 'sequel-pro'
cask 'calibre'
cask 'evernote'
cask 'dropbox'
cask 'iterm2'
cask 'intellij-idea'
cask 'kitematic'
cask 'unrarx'
cask 'spotify'
cask 'superduper'
cask 'the-unarchiver'
cask 'textmate'
cask 'whatsapp'
cask 'vlc'
cask 'transmission'
cask 'macdown'
cask 'plex-media-server'
cask 'maintenance'
cask 'basecamp'
cask 'imageoptim' # Optimize jpeg images
cask 'imagealpha' # Optimize png images
cask 'mactex' # LaTeX for Mac
cask 'spectacle' # Window management
cask 'keybase'
cask 'docker-toolbox'
cask 'soundflower'
cask 'soundflowerbed'
cask 'logitech-options'
cask 'flowsync' # Polar watch
cask 'logitech-gaming-software' # Logitech keyboard

mas 'Xcode', id: 497799835
mas 'Pages', id: 409201541
mas 'Keynote', id: 409183694
mas 'Numbers', id: 409203825
mas 'iMovie', id: 408981434
mas 'Pocket', id: 568494494
#mas 'Pixelmator', id: 407963104
mas 'Microsoft OneNote', id: 784801555
mas 'LastPass', id: 926036361
mas 'Todoist: Organize your life', id: 585829637
